### ISSUE TITLE
Questions about plpgsql function design

### ISSUE THREAD

**Issue by datarttu** [datarttu/sujuikoDB#20]
Should we strive for functional programming principles with our key data transformation functions in the sujuiko model, i.e. functions would only take a certain type of input set and return a result set, without side effects. I can imagine that this would make the functions easier to test, at least. But in reality, our functions and procedures tend to touch many parts in the database at the same time, at least as we do complex joins - that's why I've wrapped complex queries into functions in the first place.

There are some good [examples](https://github.com/datarttu/sujuikoDB/blob/dev/db/ddl/stage_hfp/journeys.sql) on perhaps-not-optimal practices in the current codebase. Table names are parameterized (and enforced to be `regclass`) in the `stage_hfp.extract_journeys_from_raw()` function, which is nice. But the function works as black box, inserting data into the journey table and only returning the number of records inserted, and then we have to go check the journey table separately if we want to inspect the results.

We could change the function so that just returns the result set, and it is up to the user or another function/procedure to insert the result to the correct table (-> added complexity). We could also change the function so that instead of table names it takes sets of data as parameter, but this would add even more complexity when invoking the function. Feeding sets of data to a function is syntactically painful if even possible in Postgres...

Note that we sometimes need to apply more complex logic inside functions than just joins, column calculations, type casts and window functions: especially with HFP data we might want to run through an ordered set of rows step by step, calculating values for the next row(s) depending on what we calculated for the previous row(s) and if they were kept or discarded as invalid.

In this light, what would be some good practices and examples when developing such functions that take raw data from multiple sources, mangle it in different ways and return a result set (eventually into a table)?

**Comment by haphut** [comment]
Pure functions warm my heart. They are a great inspiration for creating structure in non-functional paradigms, as well. "Functional core, imperative shell" and all that.

Yet PostgreSQL does not support returning a function from a function so functional programming is severely hampered.

Another aspect is that the execution plans inside functions are not shown with `EXPLAIN ANALYZE` without trickery. That makes estimating the query cost hard.

I also worry that composing many small functions might form optimization barriers for the planner and cause slow execution plans.

PostgreSQL uses the keyword `IMMUTABLE` for pure functions. Composing those is hopefully not problematic as there is no table access to worry about. I'm glad you've used `IMMUTABLE`. Keep at it! :thumbsup:

But reading from a table is already a side effect. In the linked example, there is also inserting into a table. So in that sense we might not be talking about functional programming but rather indirection by `regclass`.

I find this indirection unusual. I'm curious about what could be achieved with it but I can't recommend it.

I would rather use table names directly within the functions. For running tests, I might spin up a disposable database with a small subset of the data and check that the functions do what is expected. We don't even need to use fake data as all the data sources are open. Just pick the most problematic data sets or rows. This answer is connected to #19.

**Comment by datarttu** [comment]
Thank you again - let's discuss the function design topic in more detail next week. Just one thing before I forget to mention it: my original reason for using `regclass` instead of direct table names was that I want to be able to run functions and procedures on temporary tables. [This "master procedure"](https://github.com/datarttu/sujuikoDB/blob/dev/db/ddl/stage_hfp/import_dump.sql) is meant to handle an import process of a set of raw HFP data (say, one route and oday) all the way to the prod tables, and it uses temporary tables so that prod tables, potentially pretty large, need not be queried during the import. And, of course, there could be many different import processes running in parallel, each using its own temporary tables, isolated from each other. Inside a single import process, temp tables are referred to with fixed names (that are then passed to the functions as `regclass` arguments), but they are of course separate tables "under the hood" and will be dropped `ON COMMIT`.

I'm not sure at all if this was a clever approach (perhaps premature optimization?), and the import process currently seems so complex and bug-prone that I want to refactor it anyway. This is a good topic to discuss during the next weeks, for sure.
